version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    reviewers:
      - "openameba/spindle-working-group"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    reviewers:
      - "openameba/spindle-working-group"
