packages:
  - 'packages/*'

peerDependencyRules:
  ignoreMissing:
    - hono
  allowedVersions:
    stylelint-selector-bem-pattern>stylelint: '17'

overrides:
  superstatic: 10.0.0
  axios: 1.13.2
  undici: 7.16.0
  undici-types: 7.16.0
  semver: 7.7.3
  chokidar: 5.0.0
