name: build design tokens via webhook

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build Tokens
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_COLOR_PRIMITIVE_FILE_ID: ${{ secrets.FIGMA_COLOR_PRIMITIVE_FILE_ID }}
          FIGMA_COLOR_THEME_FILE_ID: ${{ secrets.FIGMA_COLOR_THEME_FILE_ID }}
          FIGMA_COLOR_THEME_DARK_FILE_ID: ${{ secrets.FIGMA_COLOR_THEME_DARK_FILE_ID }}
          FIGMA_DROP_SHADOW_FILE_ID: ${{ secrets.FIGMA_DROP_SHADOW_FILE_ID }}
        run: |
          pnpm --filter @openameba/spindle-tokens export
          # pnpm --filter @openameba/spindle-tokens build
          pnpm fix
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: 'feat(spindle-tokens): update design tokens'
          branch: feat/build-tokens-via-webhook
          delete-branch: true
          title: 'feat(spindle-tokens): update design tokens'
          body: ''
          labels: |
            spindle-tokens
