name: deploy Hooks catalog

on:
  push:
    branches:
      - main
    paths:
      - 'packages/spindle-hooks/**'

jobs:
  deploy_ui_catalog:
    name: deploy_ui_catalog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Update UI catalog
        run: pnpm --filter @openameba/spindle-hooks storybook:build
      - name: deploy to live channel
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          entryPoint: ./packages/spindle-hooks/
          channelId: live
