name: Check changed packages

on:
  workflow_dispatch:

jobs:
  check-changed:
    name: Check changed packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org'
      - name: Run lerna changed
        run: npx -y lerna changed
