name: test

on:
  - push
  - pull_request

env:
  TZ: Asia/Tokyo

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: |
          pnpm --filter @openameba/spindle-hooks build
          pnpm test
        env:
          CHROME_PATH: /usr/bin/google-chrome-stable

